In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
#Genrate Random data - using np randn method with 2 row and 3 column 
data = np.random.randn(2,3)

In [5]:
data

array([[ 0.55200739,  1.41696601,  1.13123051],
       [-0.84633663,  1.46943444,  2.21204535]])

In [9]:
data = data*10

In [10]:
data

array([[ 5.52007392, 14.16966006, 11.31230505],
       [-8.4633663 , 14.69434444, 22.12045351]])

In [11]:
#matrix addition
data + data

array([[ 11.04014784,  28.33932013,  22.62461011],
       [-16.92673259,  29.38868887,  44.24090701]])

In [12]:
data.shape

(2, 3)

In [14]:
data.dtype

dtype('float64')

In [16]:
data1 = [6,7,12.45,45,67, 60,89]

In [20]:
#take simple array and convert in into numpy array using builtin np.array
arr1 = np.array(data1)

In [21]:
arr1


array([ 6.  ,  7.  , 12.45, 45.  , 67.  , 60.  , 89.  ])

In [26]:
#list of objects
data2  = [[1,2,3,4],[5,6,7,8]]

In [27]:
arr2 = np.array(data2)

In [28]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [32]:
#number of rows or dimensions
arr2.ndim

2

In [33]:
arr2.shape

(2, 4)

In [35]:
arr2.dtype

dtype('int64')

In [36]:
arr1.dtype

dtype('float64')

In [37]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [42]:
#create np array with 0 to specific number in continous sequence - use arange inbuilt function
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
#explicitly giving the dtype
arr3 = np.array([1,2,3], dtype = np.float64)

In [47]:
arr3

array([1., 2., 3.])

In [48]:
arr4 = np.array([1,2,3], dtype = np.int32)

In [49]:
arr4

array([1, 2, 3], dtype=int32)