In [1]:
import numpy as np

In [2]:
arr = np.array([0,1,2,3,4,64,64,64,8,9])

In [3]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [4]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [5]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [9]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [12]:
#assigning entire slice to a specific value
arr2d[:2,1:] = 0

In [13]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])