In [16]:
import numpy as np

In [2]:
arr = np.array([0,1,2,3,4,64,64,64,8,9])

In [3]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [4]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [5]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr2d[:2,1:].shape

(2, 2)

In [9]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [12]:
#assigning entire slice to a specific value
arr2d[:2,1:] = 0

In [13]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [32]:
#boolean indexing
names = np.array(["ram", "shyam","rahul","suman","priya","shyam", "narendra"])

In [27]:
names

array(['ram', 'shyam', 'rahul', 'suman', 'priya', 'pooja', 'narendra'],
      dtype='<U8')

In [28]:
data = np.random.randn(7,4)

In [29]:
data

array([[-0.28425264,  1.7835323 , -1.84392765,  0.1642209 ],
       [-3.27772295, -0.45422709, -1.09921676,  1.8034343 ],
       [-0.30963685,  0.97936514, -1.19910195, -1.18372139],
       [ 0.92758155, -0.38947898, -0.66979092, -1.85147211],
       [ 0.97812486, -0.12530874,  1.48788433,  0.90786194],
       [-0.93091706, -0.76653803,  0.65836546, -0.2235344 ],
       [ 1.2121096 ,  0.51063579,  0.02800684,  1.69073415]])

In [30]:
names == 'pooja'

array([False, False, False, False, False,  True, False])

In [33]:
#selecting those rows who's return 
data[names=='shyam']

array([[-3.27772295, -0.45422709, -1.09921676,  1.8034343 ],
       [-0.93091706, -0.76653803,  0.65836546, -0.2235344 ]])